user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
Page_Agent:
    path:     /Page_Agent
    defaults: { _controller: UserBundle:Default:Agent }
Page_Admin:
    path:     /PageAdmin
    defaults: { _controller: UserBundle:Default:Admin }
Page_Client:
    path:     /Page_Client
    defaults: { _controller: UserBundle:Default:Client }